linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        allow:
          - $all
  goconst:
    ignore-strings: '<!doctype html>|new_|</span>'