version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

  equipment-registry-service:
    build:
      context: ../equipment-registry-service
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"

  event-monitor-service:
    build:
      context: ../event-monitor-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data: